version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
      - frontend
    networks:
      - sacco_network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./sacco_frontend:/app
      - /app/node_modules
    env_file:
      - ./.env.frontend
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sacco_network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./sacco_backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./.env.backend
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - sacco_network

  celery_worker:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    command: celery -A config worker --loglevel=info
    volumes:
      - ./sacco_backend:/app
    env_file:
      - ./.env.backend
    depends_on:
      - backend
      - rabbitmq
      - redis
    networks:
      - sacco_network

  celery_beat:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    command: celery -A config beat --loglevel=info
    volumes:
      - ./sacco_backend:/app
    env_file:
      - ./.env.backend
    depends_on:
      - backend
      - rabbitmq
      - redis
    networks:
      - sacco_network

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - sacco_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - sacco_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ./.env.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sacco_network

networks:
  sacco_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  static_volume:
  media_volume: