version: '3.8'

services:
  nginx:
    image: ${REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-kallyas/sacco}/sacco-nginx:${TAG:-main}
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
      - frontend
    networks:
      - sacco_network
    restart: always

  frontend:
    image: ${REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-kallyas/sacco}/sacco-frontend:${TAG:-main}
    platform: linux/amd64
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - ./.env.frontend
    networks:
      - sacco_network
    restart: always

  backend:
    image: ${REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-kallyas/sacco}/sacco-backend:${TAG:-main}
    platform: linux/amd64
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./.env.backend
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - sacco_network
    restart: always

  celery_worker:
    image: ${REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-kallyas/sacco}/sacco-celery:${TAG:-main}
    platform: linux/amd64
    command: celery -A config worker --loglevel=info
    env_file:
      - ./.env.backend
    depends_on:
      - backend
      - rabbitmq
      - redis
    networks:
      - sacco_network
    restart: always

  celery_beat:
    image: ${REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-kallyas/sacco}/sacco-celery:${TAG:-main}
    platform: linux/amd64
    command: celery -A config beat --loglevel=info
    env_file:
      - ./.env.backend
    depends_on:
      - backend
      - rabbitmq
      - redis
    networks:
      - sacco_network
    restart: always

  db:
    image: postgres:14-alpine
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    networks:
      - sacco_network
    restart: always

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    volumes:
      - redis_data:/data
    networks:
      - sacco_network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    platform: linux/amd64
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ./.env.rabbitmq
    networks:
      - sacco_network
    restart: always

networks:
  sacco_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  static_volume:
  media_volume: