# Generated by Django 5.1.4 on 2025-01-08 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self Employed'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('STUDENT', 'Student'), ('OTHER', 'Other')], max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('physical_address', models.TextField()),
                ('postal_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('passport_photo', models.ImageField(null=True, upload_to='member_photos/')),
                ('id_document', models.FileField(null=True, upload_to='member_documents/')),
                ('device_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('membership_status', models.CharField(default='ACTIVE', max_length=20)),
                ('membership_number', models.CharField(max_length=20, unique=True)),
                ('membership_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('JOINT', 'Joint'), ('CORPORATE', 'Corporate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID', 'National ID'), ('PASSPORT', 'Passport'), ('UTILITY_BILL', 'Utility Bill'), ('BANK_STATEMENT', 'Bank Statement'), ('OTHER', 'Other')], max_length=20)),
                ('document', models.FileField(upload_to='member_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('physical_address', models.TextField()),
                ('national_id', models.CharField(max_length=20)),
                ('percentage_share', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
