[tool.poetry]
name = "sacco-backend"
version = "0.1.0"
description = "SACCO Management System Backend"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2"
djangorestframework = "^3.14"
celery = "^5.2"
redis = "^4.5"
psycopg2-binary = "^2.9"