### GET request to example server
GET http://localhost:8000/api/v1/members/me/
Authorization: Berer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3NDQ5MDY2MjksInR5cGUiOiJhY2Nlc3MifQ.F_3XtgWWJeF6I25LCj9oWwSx7Q4weNCneFLp68-kqlc