# Generated by Django 5.1.4 on 2025-01-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('PAYMENT', 'Payment Gateway'), ('SMS', 'SMS Gateway'), ('CREDIT_BUREAU', 'Credit Bureau'), ('BANK', 'Bank Integration')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField()),
                ('api_key', models.CharField(max_length=255, null=True)),
                ('api_secret', models.CharField(max_length=255, null=True)),
                ('webhook_url', models.URLField(null=True)),
                ('webhook_secret', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('current_menu', models.CharField(max_length=50)),
                ('session_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_reference', models.CharField(max_length=50, unique=True)),
                ('provider_reference', models.CharField(max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('callback_data', models.JSONField(null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.integrationprovider')),
            ],
        ),
    ]
